-- MySQL Script generated by MySQL Workbench
-- Tue Oct  4 16:45:08 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Biblioteca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BetesdaDataBase` DEFAULT CHARACTER SET utf8 ;
USE `BetesdaDataBase` ;

-- -----------------------------------------------------
-- Table `Biblioteca`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BetesdaDataBase`.`members` (
  `idMember` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `addressNumber` VARCHAR(45) NULL,
  `neighborhood` VARCHAR(45) NULL,
   `city` VARCHAR(45) NULL,
   `zipcode` VARCHAR(45) NULL,
   `rg` VARCHAR(45) NULL,
   `cpf` VARCHAR(45) NULL,
   `dateOfBaptism` VARCHAR(45) NULL,
    `dateOfBirth` VARCHAR(45) NULL,
   `job` VARCHAR(45) NULL,
   `maritalStatus` VARCHAR(45) NULL,
   `levelAccess` INT NULL,
  PRIMARY KEY (`idMember`)
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Biblioteca`.`livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BetesdaDataBase`.`libraryCollection` (
  `idBook` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL,
  `author` VARCHAR(45) NOT NULL,
  `genre` VARCHAR(45) NOT NULL,
  `quantity` INT NOT NULL,
  `owner` VARCHAR (45) NOT NULL,
  `pending` TINYINT NOT NULL,
  PRIMARY KEY (`idBook`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Biblioteca`.`emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BetesdaDataBase`.`loan` (
  `idLoan` INT NOT NULL AUTO_INCREMENT,
  `loanDate` DATE NOT NULL,
  `returnDate` DATE NOT NULL,
  `pending` TINYINT NOT NULL,
  `idMember` INT NOT NULL,
  `idBook` INT NOT NULL,
  PRIMARY KEY (`idLoan`),
  INDEX `fk_emprestimo_members1_idx` (`idMember` ASC) ,
  INDEX `fk_emprestimo_libraryCollection1_idx` (`idBook` ASC) ,
  CONSTRAINT `fk_emprestimo_members1`
    FOREIGN KEY (`idMember`)
    REFERENCES `Biblioteca`.`members` (`idMember`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emprestimo_libraryCollection1`
    FOREIGN KEY (`idBook`)
    REFERENCES `Biblioteca`.`libraryCollection` (`idBook`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
