-- MySQL Script generated by MySQL Workbench
-- Tue Oct  4 16:45:08 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Biblioteca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Biblioteca` DEFAULT CHARACTER SET utf8 ;
USE `Biblioteca` ;

-- -----------------------------------------------------
-- Table `Biblioteca`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Biblioteca`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  `nivel` TINYINT NULL,
  PRIMARY KEY (`idUsuario`)
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Biblioteca`.`livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Biblioteca`.`livro` (
  `idLivro` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(200) NOT NULL,
  `edicao` VARCHAR(10) NOT NULL,
  `isbn` VARCHAR(45) NOT NULL,
  `imagem` LONGTEXT NOT NULL,
  `autor` VARCHAR(45) NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  `quantidade` INT NOT NULL,
  `pendente` TINYINT NOT NULL,
  PRIMARY KEY (`idLivro`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Biblioteca`.`emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Biblioteca`.`emprestimo` (
  `idEmprestimo` INT NOT NULL AUTO_INCREMENT,
  `dataEmprestimo` DATE NOT NULL,
  `dataDevolucao` DATE NOT NULL,
  `pendente` TINYINT NOT NULL,
  `idUsuario` INT NOT NULL,
  `idLivro` INT NOT NULL,
  PRIMARY KEY (`idEmprestimo`),
  INDEX `fk_emprestimo_usuario1_idx` (`idUsuario` ASC) ,
  INDEX `fk_emprestimo_livro1_idx` (`idLivro` ASC) ,
  CONSTRAINT `fk_emprestimo_usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `Biblioteca`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emprestimo_livro1`
    FOREIGN KEY (`idLivro`)
    REFERENCES `Biblioteca`.`livro` (`idLivro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Biblioteca`.`avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Biblioteca`.`avaliacao` (
  `idAvaliacao` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(150) NOT NULL,
  `idLivro` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idAvaliacao`),
  INDEX `fk_avaliacao_livro1_idx` (`idLivro` ASC),
  INDEX `fk_avaliacao_usuario1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_avaliacao_livro1`
    FOREIGN KEY (`idLivro`)
    REFERENCES `Biblioteca`.`livro` (`idLivro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avaliacao_usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `Biblioteca`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
